<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Sold Out</name>
   <tag></tag>
   <elementGuidId>83fe173c-7a79-403a-a5e5-b6ceaa753a3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.sold-out</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='product-3']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Sold Out Brown Shades Brown Shades £20.00&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6b2b0c61-f2d5-4d90-b55f-50de70def1cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sold-out</value>
      <webElementGuid>d9071864-ecad-4962-92f3-389d78a73776</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sold Out</value>
      <webElementGuid>bb16bf05-8c8c-47d5-8691-75cd77bd7f95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-3&quot;)/div[@class=&quot;sold-out&quot;]</value>
      <webElementGuid>06128fcb-c449-4a1f-8489-57c865a796b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='product-3']/div</value>
      <webElementGuid>d94a4e77-d2ae-4dfe-9537-f2972a2cc6cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='£39.99'])[1]/following::div[2]</value>
      <webElementGuid>a96d538a-097c-420c-ab2b-2e3dfc6169bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bronze sandals'])[1]/following::div[2]</value>
      <webElementGuid>cdcb1670-47a1-420d-aabe-4c48ff4ac7a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Brown Shades'])[1]/preceding::div[1]</value>
      <webElementGuid>3845371b-c13f-4183-9de3-7872465e6873</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='£20.00'])[1]/preceding::div[1]</value>
      <webElementGuid>532ae949-6388-4459-bd56-a13229792bea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sold Out']/parent::*</value>
      <webElementGuid>8e99ac1a-4e3e-4cba-9899-2aa236298e9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div</value>
      <webElementGuid>e6cc98ac-d969-485f-b2e5-961473c36cad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Sold Out' or . = 'Sold Out')]</value>
      <webElementGuid>1c3ace31-5b91-41bc-90eb-5434a5edfd40</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
